SELECT
    PATIENTPROBLEM.PATIENTPROBLEMID AS diag_id,
    PATIENTPROBLEM.CHARTID AS ndid,
    NULL AS eid,
    NULL AS encounter_date,
    CASE
        WHEN PATIENTPROBLEM.CREATEDDATETIME IS NULL
             OR PATIENTPROBLEM.CREATEDDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTPROBLEM.CREATEDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTPROBLEM.CREATEDDATETIME)
        WHEN PATIENTPROBLEM.CREATEDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.CREATEDDATETIME, '%Y-%m-%d')
        WHEN PATIENTPROBLEM.CREATEDDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.CREATEDDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS problem_date,
    CASE
        WHEN PATIENTPROBLEM.ONSETDATE IS NULL
             OR PATIENTPROBLEM.ONSETDATE IN ('', 'None')
            THEN NULL
        WHEN PATIENTPROBLEM.ONSETDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTPROBLEM.ONSETDATE)
        WHEN PATIENTPROBLEM.ONSETDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.ONSETDATE, '%Y-%m-%d')
        WHEN PATIENTPROBLEM.ONSETDATE REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.ONSETDATE, '%m-%d-%Y')
        ELSE NULL
    END AS problem_onset_date,
    CASE
        WHEN PATIENTPROBLEM.DEACTIVATEDDATETIME IS NULL
             OR PATIENTPROBLEM.DEACTIVATEDDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTPROBLEM.DEACTIVATEDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTPROBLEM.DEACTIVATEDDATETIME)
        WHEN PATIENTPROBLEM.DEACTIVATEDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.DEACTIVATEDDATETIME, '%Y-%m-%d')
        WHEN PATIENTPROBLEM.DEACTIVATEDDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTPROBLEM.DEACTIVATEDDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS problem_end_date,
    NULL AS resolved,
    SNOMED.DESCRIPTION AS problem_desc,
    PATIENTPROBLEM.SNOMEDCODE AS snomed_code,
    PATIENTPROBLEM.DIAGNOSISCODE AS icd_code,
    PATIENTPROBLEM.TYPE AS problem_type,
    PATIENTPROBLEM.STATUS AS status,
    NULL AS severity,
    PATIENTPROBLEM.LATERALITY AS laterality,
    PATIENTPROBLEM.NOTE AS problem_notes,
    "AthenaOne" AS data_source,
    10 AS psid,
    PATIENTPROBLEM.nd_extracted_date
FROM PATIENTPROBLEM
LEFT JOIN (select * from SNOMED where nd_active_flag = 'Y') SNOMED
    ON SNOMED.SNOMEDCODE = PATIENTPROBLEM.SNOMEDCODE WHERE PATIENTPROBLEM.nd_active_flag = 'Y'
UNION ALL
SELECT
    PATIENTSNOMEDPROBLEM.PATIENTSNOMEDPROBLEMID AS diag_id,
    PATIENTSNOMEDPROBLEM.CHARTID AS ndid,
    NULL AS eid,
    CASE
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME IS NULL
             OR PATIENTSNOMEDPROBLEM.ENTEREDDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME)
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME, '%Y-%m-%d')
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS encounter_date,
    CASE
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME IS NULL
             OR PATIENTSNOMEDPROBLEM.ENTEREDDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME)
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME, '%Y-%m-%d')
        WHEN PATIENTSNOMEDPROBLEM.ENTEREDDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENTEREDDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS problem_date,
    CASE
        WHEN PATIENTSNOMEDPROBLEM.STARTDATEDATETIME IS NULL
             OR PATIENTSNOMEDPROBLEM.STARTDATEDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTSNOMEDPROBLEM.STARTDATEDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTSNOMEDPROBLEM.STARTDATEDATETIME)
        WHEN PATIENTSNOMEDPROBLEM.STARTDATEDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.STARTDATEDATETIME, '%Y-%m-%d')
        WHEN PATIENTSNOMEDPROBLEM.STARTDATEDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.STARTDATEDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS problem_onset_date,
    CASE
        WHEN PATIENTSNOMEDPROBLEM.ENDDATEDATETIME IS NULL
             OR PATIENTSNOMEDPROBLEM.ENDDATEDATETIME IN ('', 'None')
            THEN NULL
        WHEN PATIENTSNOMEDPROBLEM.ENDDATEDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(PATIENTSNOMEDPROBLEM.ENDDATEDATETIME)
        WHEN PATIENTSNOMEDPROBLEM.ENDDATEDATETIME REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENDDATEDATETIME, '%Y-%m-%d')
        WHEN PATIENTSNOMEDPROBLEM.ENDDATEDATETIME REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(PATIENTSNOMEDPROBLEM.ENDDATEDATETIME, '%m-%d-%Y')
        ELSE NULL
    END AS problem_end_date,
    NULL AS resolved,
    SNOMED.DESCRIPTION AS problem_desc,
    PATIENTSNOMEDPROBLEM.SNOMEDCODE AS snomed_code,
    NULL AS icd_code,
    NULL AS problem_type,
    NULL AS status,
    PATIENTSNOMEDPROBLEM.SEVERITY AS severity,
    PATIENTSNOMEDPROBLEM.LATERALITY AS laterality,
    PATIENTSNOMEDPROBLEM.PROBLEMNOTE AS problem_notes,
    "AthenaOne 2" AS data_source,
    10 AS psid,
    PATIENTSNOMEDPROBLEM.nd_extracted_date
FROM PATIENTSNOMEDPROBLEM
LEFT JOIN (select * from SNOMED where nd_active_flag = 'Y') SNOMED
    ON SNOMED.SNOMEDCODE = PATIENTSNOMEDPROBLEM.SNOMEDCODE WHERE PATIENTSNOMEDPROBLEM.nd_active_flag = 'Y'
UNION ALL
SELECT
    PATIENTSNOMEDICD10.PATIENTSNOMEDICD10ID AS diag_id,
    PATIENTSNOMEDICD10.CHARTID AS ndid,
    PATIENTSNOMEDICD10.CLINICALENCOUNTERID AS eid,
    CASE
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE IS NULL
             OR CLINICALENCOUNTER.ENCOUNTERDATE IN ('', 'None')
            THEN NULL
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(CLINICALENCOUNTER.ENCOUNTERDATE)
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(CLINICALENCOUNTER.ENCOUNTERDATE, '%Y-%m-%d')
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(CLINICALENCOUNTER.ENCOUNTERDATE, '%m-%d-%Y')
        ELSE NULL
    END AS encounter_date,
    CASE
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE IS NULL
             OR CLINICALENCOUNTER.ENCOUNTERDATE IN ('', 'None')
            THEN NULL
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
            THEN DATE(CLINICALENCOUNTER.ENCOUNTERDATE)
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
            THEN STR_TO_DATE(CLINICALENCOUNTER.ENCOUNTERDATE, '%Y-%m-%d')
        WHEN CLINICALENCOUNTER.ENCOUNTERDATE REGEXP '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
            THEN STR_TO_DATE(CLINICALENCOUNTER.ENCOUNTERDATE, '%m-%d-%Y')
        ELSE NULL
    END AS problem_date,
    NULL AS problem_onset_date,
    NULL AS problem_end_date,
    NULL AS resolved,
    SNOMED.DESCRIPTION AS problem_desc,
    PATIENTSNOMEDICD10.SNOMEDCODE AS snomed_code,
    ICDCODEALL.DIAGNOSISCODE AS icd_code,
    NULL AS problem_type,
    NULL AS status,
    NULL AS severity,
    NULL AS laterality,
    NULL AS problem_notes,
    "AthenaOne 3" AS data_source,
    10 AS psid,
    PATIENTSNOMEDICD10.nd_extracted_date
FROM PATIENTSNOMEDICD10
LEFT JOIN (select * from SNOMED where nd_active_flag = 'Y') SNOMED
    ON SNOMED.SNOMEDCODE = PATIENTSNOMEDICD10.SNOMEDCODE 
LEFT JOIN (SELECT * FROM CLINICALENCOUNTER where nd_active_flag = 'Y') CLINICALENCOUNTER
        ON CLINICALENCOUNTER.CLINICALENCOUNTERID=PATIENTSNOMEDICD10.CLINICALENCOUNTERID
LEFT JOIN (SELECT * FROM ICDCODEALL where nd_active_flag = 'Y') ICDCODEALL
        ON ICDCODEALL.ICDCODEID=PATIENTSNOMEDICD10.ICDCODEALLID where PATIENTSNOMEDICD10.nd_active_flag = 'Y';