CREATE TABLE `patients` (
  `ndid` bigint NOT NULL,
  `clinicid` varchar(200) DEFAULT NULL,
  `registration_date` datetime DEFAULT NULL,
  `dob` int DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `pat_language` varchar(255) NOT NULL,
  `pat_city` varchar(200) DEFAULT NULL,
  `pat_state` varchar(10) DEFAULT NULL,
  `pat_country` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `pat_zip` varchar(50) DEFAULT NULL,
  `pat_race_code` char(15) DEFAULT NULL,
  `pat_race` char(100) DEFAULT NULL,
  `pat_ethnicity_code` varchar(100) DEFAULT NULL,
  `pat_ethnicity` varchar(25) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `pat_marital_status` varchar(30) NOT NULL,
  `pat_deceased_status` varchar(5) DEFAULT NULL,
  `deceased_date` datetime DEFAULT NULL,
  `deceased_reason` varchar(200) DEFAULT NULL,
  `primary_provider_id` int DEFAULT NULL,
  `ehr_active_flag` varchar(5) DEFAULT NULL,
  `pat_insurance` varchar(200) DEFAULT NULL,
  `pcp_name` varchar(50) NOT NULL DEFAULT '',
  `rendering_provider_id` varchar(20) DEFAULT NULL,
  `referring_provider_id` varchar(20) DEFAULT NULL,
  `disability_status` varchar(50) NOT NULL DEFAULT '',
  `residence_type` varchar(50) NOT NULL DEFAULT '',
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(50) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(15) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL,
  `referral_flag` varchar(100) DEFAULT NULL,
  `referral_from` char(10) DEFAULT NULL,
  `test_pat_flag` char(10) DEFAULT NULL,
  `udm_inc_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nd_extracted_date` date DEFAULT NULL,
  `gender_hl7_std` varchar(50) DEFAULT NULL,
  `gender_CDISC_std` varchar(50) DEFAULT NULL,
  `gender_OMOP_std` varchar(50) DEFAULT NULL,
  `gender_OMOP_concept_id` varchar(50) DEFAULT NULL,
  `pat_race_code_std` varchar(500) DEFAULT NULL,
  `pat_race_std` varchar(500) DEFAULT NULL,
  `pat_ethnicity_code_std` varchar(500) DEFAULT NULL,
  `pat_ethnicity_std` varchar(500) DEFAULT NULL,
  `pat_deceased_status_std` varchar(500) DEFAULT NULL,
  `enc_date_proxy` date DEFAULT NULL,
  `pat_marital_status_std` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ndid`,`psid`),
  UNIQUE KEY `udm_inc_id` (`udm_inc_id`),
  UNIQUE KEY `uk_ndid` (`ndid`,`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_ds` (`pat_deceased_status`),
  KEY `idx_gn` (`gender`),
  KEY `idx_dob` (`dob`)
) ENGINE=InnoDB AUTO_INCREMENT=13648649 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `encounters` (
  `eid` bigint DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `enc_end_date` date DEFAULT NULL,
  `enc_start_time` time DEFAULT NULL,
  `enc_end_time` time DEFAULT NULL,
  `encounter_category` varchar(50) DEFAULT NULL,
  `enc_type` varchar(50) DEFAULT NULL,
  `enc_reason` text,
  `enc_appt_id` decimal(18,0) DEFAULT NULL,
  `enc_department` varchar(30) DEFAULT NULL,
  `doc_speciality` varchar(60) DEFAULT NULL,
  `enc_facility_id` varchar(200) DEFAULT NULL,
  `enc_location` varchar(30) DEFAULT NULL,
  `enc_status` varchar(30) DEFAULT NULL,
  `enc_document_flg` char(2) DEFAULT NULL,
  `enc_document_id` varchar(50) DEFAULT NULL,
  `pregnancy_flg` char(1) DEFAULT NULL,
  `inpatient_flg` char(1) DEFAULT NULL,
  `provider_id` varchar(30) DEFAULT NULL,
  `supervising_provider_id` varchar(100) DEFAULT NULL,
  `primary_provider_id` varchar(100) DEFAULT NULL,
  `referral_flg` varchar(15) DEFAULT NULL,
  `referring_provider_id` varchar(30) DEFAULT NULL,
  `referring_provider_name` varchar(255) DEFAULT NULL,
  `referring_provider_npi` varchar(255) DEFAULT NULL,
  `locked` char(1) DEFAULT NULL,
  `provider_name` varchar(200) DEFAULT NULL,
  `care_team` varchar(200) DEFAULT NULL,
  `payer` varchar(100) DEFAULT NULL,
  `referral_reason` varchar(200) DEFAULT NULL,
  `visit_type` varchar(50) DEFAULT NULL,
  `rendering_provider_name` varchar(200) DEFAULT NULL,
  `created_datetime` date NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(50) DEFAULT NULL,
  `source_path` varchar(50) DEFAULT NULL,
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_encounters_udm_inc_id` (`udm_inc_id`),
  KEY `idx_encounters_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_enc_dt` (`enc_date`)
) ENGINE=InnoDB AUTO_INCREMENT=240697669 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `diagnosis` (
  `diag_id` varchar(100) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `encounter_end_date` date DEFAULT NULL,
  `diag_date` date DEFAULT NULL,
  `diag_code` varchar(10) NOT NULL,
  `diag_desc` longtext,
  `diag_coding_system` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_code_stripped` varchar(10) NOT NULL DEFAULT '',
  `primary_diagnosis_flag` varchar(10) DEFAULT NULL,
  `parent_diagnosis_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_diagnosis_desc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_desc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_group` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_system` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snomed_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_severity` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_status` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_end_date` date DEFAULT NULL,
  `provisional_diag_flag` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `differential_diag_flag` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comments_notes` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_risk` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `specify` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `created_datetime` date DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `ehr_source_name` varchar(15) DEFAULT NULL,
  `source_path` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  `icd10_desc_std` text,
  `icd9_desc_std` text,
  `diag_coding_system_std` varchar(50) DEFAULT NULL,
  `primary_diagnosis_flag_std` varchar(10) DEFAULT NULL,
  `diag_desc_std` text,
  UNIQUE KEY `UQ_diagnosis_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_diagnosis_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_dg_cd` (`diag_code`),
  KEY `idx_enc_dt` (`diag_date`)
) ENGINE=InnoDB AUTO_INCREMENT=79698984 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `procedures` (
  `proc_id` varchar(40) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `encounter_date` date DEFAULT NULL,
  `proc_start_date` date DEFAULT NULL,
  `proc_last_date` date DEFAULT NULL,
  `proc_category` varchar(100) DEFAULT NULL,
  `proc_code` varchar(20) DEFAULT NULL,
  `proc_name` varchar(255) DEFAULT NULL,
  `proc_coding_system` varchar(30) DEFAULT NULL,
  `proc_units` varchar(60) DEFAULT NULL,
  `proc_description` varchar(255) DEFAULT NULL,
  `proc_notes` varchar(60) DEFAULT NULL,
  `anesthesia_flag` varchar(60) DEFAULT NULL,
  `anesthesia_detail_id` varchar(60) DEFAULT NULL,
  `ordering_provider_id` varchar(60) DEFAULT NULL,
  `ordering_provider_name` varchar(60) DEFAULT NULL,
  `ordering_provider_npi` varchar(60) DEFAULT NULL,
  `rendering_provider_id` varchar(60) DEFAULT NULL,
  `rendering_provider_name` varchar(60) DEFAULT NULL,
  `rendering_provider_npi` varchar(60) DEFAULT NULL,
  `referring_provider_id` varchar(100) DEFAULT NULL,
  `referring_provider_name` varchar(60) DEFAULT NULL,
  `referring_provider_npi` varchar(60) DEFAULT NULL,
  `place_of_service_Id` varchar(60) DEFAULT NULL,
  `place_of_service_desc` varchar(100) DEFAULT NULL,
  `order_date` varchar(20) DEFAULT NULL,
  `Diagnosis_Indication` varchar(20) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `created_datetime` date NOT NULL,
  `created_by` varchar(10) DEFAULT NULL,
  `ehr_source_name` varchar(20) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `incremental_id` bigint unsigned DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `proc_code_std` varchar(500) DEFAULT NULL,
  `proc_coding_system_std` varchar(500) DEFAULT NULL,
  `enc_date_proxy` date DEFAULT NULL,
  `proc_modifier_std` varchar(100) DEFAULT NULL,
  `proc_name_std` longtext,
  `proc_description_std` longtext,
  UNIQUE KEY `UQ_procedures_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_proc_name` (`proc_name`,`ndid`,`encounter_date`,`proc_start_date`),
  KEY `idx_psid` (`psid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_backfill` (`incremental_id`,`encounter_date`,`eid`),
  KEY `idx_proc_code` (`proc_code`)
) ENGINE=InnoDB AUTO_INCREMENT=81656254 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `medications_part1` (
  `source` varchar(100) DEFAULT NULL,
  `med_id` int DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `written_date` date DEFAULT NULL,
  `med_administered_datetime` datetime DEFAULT NULL,
  `doc_orderdatetime` datetime DEFAULT NULL,
  `med_start_date` date DEFAULT NULL,
  `med_end_date` date DEFAULT NULL,
  `med_createddatetime` datetime DEFAULT NULL,
  `doc_createddatetime` datetime DEFAULT NULL,
  `last_dispensed_date` date DEFAULT NULL,
  `sample_expiration_date` date DEFAULT NULL,
  `administer_expiration_date` date DEFAULT NULL,
  `earliest_fill_date` date DEFAULT NULL,
  `med_code` varchar(255) DEFAULT NULL,
  `med_name` varchar(255) DEFAULT NULL,
  `med_coding_system` varchar(30) DEFAULT NULL,
  `med_status` varchar(24) DEFAULT NULL,
  `med_status_flag` varchar(15) DEFAULT NULL,
  `med_indication` varchar(500) DEFAULT NULL,
  `med_formulation` text,
  `med_route` text,
  `med_strength` text,
  `med_strength_unit` varchar(50) DEFAULT NULL,
  `med_frequency` text,
  `med_pb_qty` text,
  `med_days_supply` text,
  `med_refills` text,
  `med_directions` longtext,
  `fill_date` datetime DEFAULT NULL,
  `med_fill_type` varchar(50) DEFAULT NULL,
  `discont_date` date DEFAULT NULL,
  `discont_reason` varchar(250) DEFAULT NULL,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `updated_datetime` date DEFAULT NULL,
  `updated_by` varchar(15) DEFAULT NULL,
  `ehr_source_name` varchar(100) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_medication_udm_inc_id` (`udm_inc_id`),
  KEY `idx_eid` (`eid`),
  KEY `idx_mdcd` (`med_code`),
  KEY `idx_mdds` (`med_name`),
  KEY `idx_medications` (`psid`) USING BTREE,
  KEY `idx_ndid` (`ndid`),
  KEY `idx_med_start_date` (`med_start_date`),
  KEY `idx_enc_date` (`enc_date`)
) ENGINE=InnoDB AUTO_INCREMENT=381946598 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `medications_part2` (
  `source` varchar(100) DEFAULT NULL,
  `med_id` bigint DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `written_date` date DEFAULT NULL,
  `med_administered_datetime` datetime DEFAULT NULL,
  `doc_orderdatetime` datetime DEFAULT NULL,
  `med_start_date` date DEFAULT NULL,
  `med_end_date` date DEFAULT NULL,
  `med_createddatetime` datetime DEFAULT NULL,
  `doc_createddatetime` datetime DEFAULT NULL,
  `last_dispensed_date` date DEFAULT NULL,
  `sample_expiration_date` date DEFAULT NULL,
  `administer_expiration_date` date DEFAULT NULL,
  `earliest_fill_date` date DEFAULT NULL,
  `med_code` varchar(255) DEFAULT NULL,
  `med_name` varchar(255) DEFAULT NULL,
  `med_coding_system` varchar(30) DEFAULT NULL,
  `med_status` varchar(24) DEFAULT NULL,
  `med_status_flag` varchar(15) DEFAULT NULL,
  `med_indication` varchar(500) DEFAULT NULL,
  `med_formulation` text,
  `med_route` text,
  `med_strength` text,
  `med_strength_unit` varchar(50) DEFAULT NULL,
  `med_frequency` text,
  `med_pb_qty` text,
  `med_days_supply` text,
  `med_refills` text,
  `med_directions` longtext,
  `fill_date` datetime DEFAULT NULL,
  `med_fill_type` varchar(50) DEFAULT NULL,
  `discont_date` date DEFAULT NULL,
  `discont_reason` varchar(250) DEFAULT NULL,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `updated_datetime` date DEFAULT NULL,
  `updated_by` varchar(15) DEFAULT NULL,
  `ehr_source_name` varchar(100) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_medication_udm_inc_id` (`udm_inc_id`),
  KEY `idx_eid` (`eid`),
  KEY `idx_mdcd` (`med_code`),
  KEY `idx_mdds` (`med_name`),
  KEY `idx_medications` (`psid`) USING BTREE,
  KEY `idx_ndid` (`ndid`),
  KEY `idx_med_start_date` (`med_start_date`),
  KEY `idx_enc_date` (`enc_date`)
) ENGINE=InnoDB AUTO_INCREMENT=54080341 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ros` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `ros_date` date DEFAULT NULL,
  `ros_name` varchar(255) DEFAULT NULL,
  `ros_category` varchar(255) DEFAULT NULL,
  `ros_option` longtext,
  `ros_notes` longtext,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(15) DEFAULT NULL,
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `ros_id` varchar(255) DEFAULT NULL,
  `ros_parameter` varchar(255) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_ros_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_ros_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=138247569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `examination` (
  `examid` varchar(30) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `exam_date` date DEFAULT NULL,
  `exam_category` varchar(255) DEFAULT NULL,
  `exam_name` varchar(255) DEFAULT NULL,
  `exam_findings` longtext,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(30) DEFAULT NULL,
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `finding_type` varchar(5000) DEFAULT NULL,
  `exam_parameters` varchar(500) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_examination_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_examinations_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=93556024 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `notes_part1` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `note` longtext,
  `note_type` longtext,
  `note_source` varchar(26) NOT NULL DEFAULT '',
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_notes_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_notes_ndid_eid` (`ndid`,`eid`),
  KEY `idx_notes_extracted_date` (`nd_extracted_date`),
  KEY `idx_psid` (`psid`),
  KEY `idx_notes_psid_ndid` (`psid`,`ndid`),
  KEY `idx_biogen_enc_start_date` (`enc_start_date`)
) ENGINE=InnoDB AUTO_INCREMENT=142239506 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `notes_part2` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `note` longtext,
  `note_type` longtext,
  `note_source` varchar(26) NOT NULL DEFAULT '',
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `enc_date_proxy` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  UNIQUE KEY `udm_inc_id_new` (`udm_inc_id`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_notes_psid_ndid` (`psid`,`ndid`),
  KEY `idx_biogen_enc_start_date` (`enc_start_date`)
) ENGINE=InnoDB AUTO_INCREMENT=177931914 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `vitals` (
  `vital_id` decimal(18,0) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `vital_code` int DEFAULT NULL,
  `vital_name` varchar(100) DEFAULT NULL,
  `vital_coding_system` varchar(10) DEFAULT NULL,
  `vital_date` varchar(10) DEFAULT NULL,
  `vital_time` varchar(13) DEFAULT NULL,
  `vital_unit` varchar(60) DEFAULT NULL,
  `vital_range` binary(0) DEFAULT NULL,
  `vital_result` varchar(500) DEFAULT NULL,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `updated_datetime` datetime DEFAULT NULL,
  `updated_by` varchar(2) DEFAULT NULL,
  `ehr_source_name` varchar(255) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` varchar(4) NOT NULL DEFAULT '',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_vitals_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_vitals_29012026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=298530299 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `labs` (
  `result_id` bigint DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `lab_order_date` date DEFAULT NULL,
  `sample_collection_date` date DEFAULT NULL,
  `result_date` date DEFAULT NULL,
  `result_name` text,
  `result_parameter` text,
  `result_code` text,
  `result_coding_system` varchar(5) DEFAULT NULL,
  `result_value` longtext NOT NULL,
  `result_unit` longtext NOT NULL,
  `result_range` longtext NOT NULL,
  `result_value_type` char(0) NOT NULL DEFAULT '',
  `ordering_provider_name` varchar(100) DEFAULT NULL,
  `order_id` char(0) NOT NULL DEFAULT '',
  `test_performing_lab_id` longtext NOT NULL,
  `test_performing_lab_name` varchar(100) DEFAULT NULL,
  `normalcy_flag` varchar(100) DEFAULT NULL,
  `result_status` longtext NOT NULL,
  `report_id` varchar(50) DEFAULT NULL,
  `report_status` longtext NOT NULL,
  `report_description` longtext NOT NULL,
  `specimen_source` longtext NOT NULL,
  `specimen_number` char(0) NOT NULL DEFAULT '',
  `internal_note` longtext NOT NULL,
  `note_to_patient` longtext,
  `facility` varchar(20) DEFAULT NULL,
  `interpretation` varchar(20) DEFAULT NULL,
  `received` varchar(100) DEFAULT NULL,
  `highpriority` varchar(20) DEFAULT NULL,
  `cancelled` varchar(10) DEFAULT NULL,
  `futureorder` varchar(10) DEFAULT NULL,
  `inhouse` varchar(10) DEFAULT NULL,
  `ordered_fasting` varchar(10) DEFAULT NULL,
  `do_not_publish_to_patient` varchar(10) DEFAULT NULL,
  `interfacestatus` char(0) NOT NULL DEFAULT '',
  `created_datetime` date NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `Result_Document_ID` double DEFAULT NULL,
  `Report_date` datetime DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_labs_udm_inc_id` (`udm_inc_id`),
  KEY `idx_eid` (`eid`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_resdt` (`result_date`),
  KEY `id_resultid` (`result_id`)
) ENGINE=InnoDB AUTO_INCREMENT=91182365 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `radiology` (
  `result_id` varchar(30) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` datetime DEFAULT NULL,
  `img_date` varchar(100) DEFAULT NULL,
  `study_name` varchar(255) DEFAULT NULL,
  `modality` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `img_status` varchar(30) DEFAULT NULL,
  `img_report_text` longtext,
  `img_finding` longtext,
  `report_id` varchar(30) DEFAULT NULL,
  `report_date` varchar(100) DEFAULT NULL,
  `report_status` varchar(15) DEFAULT NULL,
  `img_reason` longtext,
  `order_date` date DEFAULT NULL,
  `order_status` varchar(30) DEFAULT NULL,
  `order_prescription` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_id` varchar(20) DEFAULT NULL,
  `provider_name` varchar(130) DEFAULT NULL,
  `provider_npi` varchar(30) DEFAULT NULL,
  `internal_notes` text,
  `note_to_patient` text,
  `facility` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interpretation` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `report_text` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_datetime` date DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_radiology_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_psid` (`psid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_result_id` (`result_id`),
  KEY `idx_enc_date_proxy` (`enc_date_proxy`)
) ENGINE=InnoDB AUTO_INCREMENT=6081308 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

