SELECT 
       O.OBSID, -- Primary FHIR Resource ID must go first
    O.PID,
       O.XID,
       O.CHANGE, 
       O.SDID,
       O.USRID,
       O.HDID,
       O.ABNORMAL,
       O.OBSDATE,
       O.OBSTYPE,
       O.OBSVALUE,
       O.PUBUSER,
       O.PUBTIME,
       O.PARENTID,
       O.RANGE,
       O.DESCRIPTION,
       CASE WHEN O.STATE IS NULL OR O.STATE ='' 
                     THEN
                           'F'
                     ELSE
                           O.STATE
                     
                     END AS STATE, 
       O.ENTRYID,
       O.ARCHIVE, 
       O.DB_CREATE_DATE,
       O.DB_UPDATED_DATE,
       H.NAME,
       H.UNIT,
       H.DESCRIPTION AS OBSHEAD_DESCRIPTION,
       HG.GROUPNAME AS HG_GROUPNAME,
       HG.GROUPID AS HG_GROUPID,
       PT.SENSITIVECHART,
       C1.CODE AS C1_CODE,
       C1.CODING_SYSTEM_NAME AS C1_CODING_SYSTEM_NAME,
       C1.DESCRIPTION AS C1_DESCRIPTION,
       C2.CODE AS C2_CODE,
       C2.CODING_SYSTEM_NAME AS C2_CODING_SYSTEM_NAME,
       C2.DESCRIPTION AS C2_DESCRIPTION,
       CN.ABBR AS CONFABBR,
       ISNULL(CN.CONFTYPEID,0) AS CONFTYPEID,
       LOP.CODE AS LOP_CODE,
       LOP.CODETYPE AS LOP_CODETYPE,
       LOP.NAME AS LOP_NAME,
       PT.LOCATIONID AS LOCATIONID
       FROM OBS O
            JOIN PATIENTPROFILE PT ON PT.PID = O.PID
            JOIN DOCUMENT D ON D.SDID = O.SDID
            JOIN CONFTYPES CN ON D.CONFTYPE = CN.CONFTYPEID
            JOIN OBSHEAD H ON H.HDID = O.HDID
            JOIN HIERGRPS HG ON HG.GROUPID = H.GROUPID
            LEFT JOIN  REL_OBS_EXT_CODE R1 ON O.OBSID = R1.OBSID AND R1.EXT_CODE_ORDER = 1
            LEFT JOIN  REL_OBS_EXT_CODE R2 ON O.OBSID = R2.OBSID AND R2.EXT_CODE_ORDER = 2
            LEFT JOIN EXT_CODE C1 ON C1.EXT_CODE_ID = R1.EXT_CODE_ID
            LEFT JOIN EXT_CODE C2 ON C2.EXT_CODE_ID = R2.EXT_CODE_ID
            LEFT JOIN LABORDERPANEL LOP ON LOP.LABORDERPANELID = O.LABORDERPANELID
       WHERE (O.XID = 1E18 OR (O.CHANGE IN (0,4,10) AND NOT EXISTS (SELECT 1 FROM OBS O2 WHERE O.PID = O2.PID AND O.XID = O2.OBSID)))
       AND H.GROUPID=1300;