CREATE TABLE `encounters` (
  `eid` bigint DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `enc_end_date` date DEFAULT NULL,
  `enc_start_time` time DEFAULT NULL,
  `enc_end_time` time DEFAULT NULL,
  `encounter_category` varchar(50) DEFAULT NULL,
  `enc_type` varchar(50) DEFAULT NULL,
  `enc_reason` text,
  `enc_appt_id` decimal(18,0) DEFAULT NULL,
  `enc_department` varchar(30) DEFAULT NULL,
  `doc_speciality` varchar(60) DEFAULT NULL,
  `enc_facility_id` varchar(200) DEFAULT NULL,
  `enc_location` varchar(30) DEFAULT NULL,
  `enc_status` varchar(30) DEFAULT NULL,
  `enc_document_flg` char(2) DEFAULT NULL,
  `enc_document_id` varchar(50) DEFAULT NULL,
  `pregnancy_flg` char(1) DEFAULT NULL,
  `inpatient_flg` char(1) DEFAULT NULL,
  `provider_id` varchar(30) DEFAULT NULL,
  `supervising_provider_id` varchar(100) DEFAULT NULL,
  `primary_provider_id` varchar(100) DEFAULT NULL,
  `referral_flg` varchar(15) DEFAULT NULL,
  `referring_provider_id` varchar(30) DEFAULT NULL,
  `referring_provider_name` varchar(255) DEFAULT NULL,
  `referring_provider_npi` varchar(255) DEFAULT NULL,
  `locked` char(1) DEFAULT NULL,
  `provider_name` varchar(200) DEFAULT NULL,
  `care_team` varchar(200) DEFAULT NULL,
  `payer` varchar(100) DEFAULT NULL,
  `referral_reason` varchar(200) DEFAULT NULL,
  `visit_type` varchar(50) DEFAULT NULL,
  `rendering_provider_name` varchar(200) DEFAULT NULL,
  `created_datetime` date NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(50) DEFAULT NULL,
  `source_path` varchar(50) DEFAULT NULL,
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_encounters_udm_inc_id` (`udm_inc_id`),
  KEY `idx_encounters_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_enc_dt` (`enc_date`)
) ENGINE=InnoDB AUTO_INCREMENT=240699790 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `diagnosis` (
  `diag_id` varchar(100) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `encounter_end_date` date DEFAULT NULL,
  `diag_date` date DEFAULT NULL,
  `diag_code` varchar(10) NOT NULL,
  `diag_desc` longtext,
  `diag_coding_system` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_code_stripped` varchar(10) NOT NULL DEFAULT '',
  `primary_diagnosis_flag` varchar(10) DEFAULT NULL,
  `parent_diagnosis_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parent_diagnosis_desc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_desc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_group` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icd_codeset_system` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snomed_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_severity` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_status` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_end_date` date DEFAULT NULL,
  `provisional_diag_flag` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `differential_diag_flag` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comments_notes` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diag_risk` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `specify` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `created_datetime` date DEFAULT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `ehr_source_name` varchar(15) DEFAULT NULL,
  `source_path` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  `icd10_desc_std` text,
  `icd9_desc_std` text,
  `diag_coding_system_std` varchar(50) DEFAULT NULL,
  `primary_diagnosis_flag_std` varchar(10) DEFAULT NULL,
  UNIQUE KEY `UQ_diagnosis_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_diagnosis_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_dg_cd` (`diag_code`),
  KEY `idx_enc_dt` (`diag_date`)
) ENGINE=InnoDB AUTO_INCREMENT=79698984 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `procedures` (
  `proc_id` varchar(40) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `encounter_date` date DEFAULT NULL,
  `proc_start_date` date DEFAULT NULL,
  `proc_last_date` date DEFAULT NULL,
  `proc_category` varchar(100) DEFAULT NULL,
  `proc_code` varchar(20) DEFAULT NULL,
  `proc_name` varchar(255) DEFAULT NULL,
  `proc_coding_system` varchar(30) DEFAULT NULL,
  `proc_units` varchar(60) DEFAULT NULL,
  `proc_description` varchar(255) DEFAULT NULL,
  `proc_notes` varchar(60) DEFAULT NULL,
  `anesthesia_flag` varchar(60) DEFAULT NULL,
  `anesthesia_detail_id` varchar(60) DEFAULT NULL,
  `ordering_provider_id` varchar(60) DEFAULT NULL,
  `ordering_provider_name` varchar(60) DEFAULT NULL,
  `ordering_provider_npi` varchar(60) DEFAULT NULL,
  `rendering_provider_id` varchar(60) DEFAULT NULL,
  `rendering_provider_name` varchar(60) DEFAULT NULL,
  `rendering_provider_npi` varchar(60) DEFAULT NULL,
  `referring_provider_id` varchar(100) DEFAULT NULL,
  `referring_provider_name` varchar(60) DEFAULT NULL,
  `referring_provider_npi` varchar(60) DEFAULT NULL,
  `place_of_service_Id` varchar(60) DEFAULT NULL,
  `place_of_service_desc` varchar(100) DEFAULT NULL,
  `order_date` varchar(20) DEFAULT NULL,
  `Diagnosis_Indication` varchar(20) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `created_datetime` date NOT NULL,
  `created_by` varchar(10) DEFAULT NULL,
  `ehr_source_name` varchar(20) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `incremental_id` bigint unsigned DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `proc_code_std` varchar(500) DEFAULT NULL,
  `proc_coding_system_std` varchar(500) DEFAULT NULL,
  `enc_date_proxy` date DEFAULT NULL,
  `proc_modifier_std` varchar(100) DEFAULT NULL,
  `proc_name_std` longtext,
  `proc_description_std` longtext,
  UNIQUE KEY `UQ_procedures_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_proc_name` (`proc_name`,`ndid`,`encounter_date`,`proc_start_date`),
  KEY `idx_psid` (`psid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_backfill` (`incremental_id`,`encounter_date`,`eid`),
  KEY `idx_proc_code` (`proc_code`)
) ENGINE=InnoDB AUTO_INCREMENT=81656843 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `allergies` (
  `allergy_id` decimal(18,0) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `allergy_onset_date` varchar(25) DEFAULT NULL,
  `allergy_end_date` date DEFAULT NULL,
  `allergy_type` varchar(200) DEFAULT NULL,
  `allergen_name` longtext,
  `allergen_code` varchar(25) DEFAULT NULL,
  `allergen_coding_system` varchar(10) DEFAULT NULL,
  `allergy_reaction_name` longtext,
  `allergy_reaction_code` text,
  `allergy_reaction_coding_system` varchar(100) DEFAULT NULL,
  `allergy_severity` varchar(30) DEFAULT NULL,
  `allergy_route` varchar(50) DEFAULT NULL,
  `allergy_status` varchar(50) DEFAULT NULL,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `updated_datetime` datetime DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `ehr_source_name` varchar(100) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` varchar(4) NOT NULL DEFAULT '',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_allergies_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_psid` (`psid`)
) ENGINE=InnoDB AUTO_INCREMENT=14745460 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `vitals` (
  `vital_id` decimal(18,0) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `vital_code` int DEFAULT NULL,
  `vital_name` varchar(100) DEFAULT NULL,
  `vital_coding_system` varchar(10) DEFAULT NULL,
  `vital_date` varchar(10) DEFAULT NULL,
  `vital_time` varchar(13) DEFAULT NULL,
  `vital_unit` varchar(60) DEFAULT NULL,
  `vital_range` binary(0) DEFAULT NULL,
  `vital_result` varchar(500) DEFAULT NULL,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `updated_datetime` datetime DEFAULT NULL,
  `updated_by` varchar(2) DEFAULT NULL,
  `ehr_source_name` varchar(255) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` varchar(4) NOT NULL DEFAULT '',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_vitals_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_vitals_29012026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=285637373 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `notes_part1` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `note` longtext,
  `note_type` longtext,
  `note_source` varchar(26) NOT NULL DEFAULT '',
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_notes_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_notes_ndid_eid` (`ndid`,`eid`),
  KEY `idx_notes_extracted_date` (`nd_extracted_date`),
  KEY `idx_psid` (`psid`),
  KEY `idx_notes_psid_ndid` (`psid`,`ndid`)
) ENGINE=InnoDB AUTO_INCREMENT=142239506 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notes_part2` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `note` longtext,
  `note_type` longtext,
  `note_source` varchar(26) NOT NULL DEFAULT '',
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `enc_date_proxy` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  UNIQUE KEY `udm_inc_id_new` (`udm_inc_id`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_notes_psid_ndid` (`psid`,`ndid`)
) ENGINE=InnoDB AUTO_INCREMENT=177931914 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `labs` (
  `result_id` bigint DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` date DEFAULT NULL,
  `lab_order_date` date DEFAULT NULL,
  `sample_collection_date` date DEFAULT NULL,
  `result_date` date DEFAULT NULL,
  `result_name` text,
  `result_parameter` text,
  `result_code` text,
  `result_coding_system` varchar(5) DEFAULT NULL,
  `result_value` longtext NOT NULL,
  `result_unit` longtext NOT NULL,
  `result_range` longtext NOT NULL,
  `result_value_type` char(0) NOT NULL DEFAULT '',
  `ordering_provider_name` varchar(100) DEFAULT NULL,
  `order_id` char(0) NOT NULL DEFAULT '',
  `test_performing_lab_id` longtext NOT NULL,
  `test_performing_lab_name` varchar(100) DEFAULT NULL,
  `normalcy_flag` varchar(100) DEFAULT NULL,
  `result_status` longtext NOT NULL,
  `report_id` varchar(50) DEFAULT NULL,
  `report_status` longtext NOT NULL,
  `report_description` longtext NOT NULL,
  `specimen_source` longtext NOT NULL,
  `specimen_number` char(0) NOT NULL DEFAULT '',
  `internal_note` longtext NOT NULL,
  `note_to_patient` longtext,
  `facility` varchar(20) DEFAULT NULL,
  `interpretation` varchar(20) DEFAULT NULL,
  `received` varchar(100) DEFAULT NULL,
  `highpriority` varchar(20) DEFAULT NULL,
  `cancelled` varchar(10) DEFAULT NULL,
  `futureorder` varchar(10) DEFAULT NULL,
  `inhouse` varchar(10) DEFAULT NULL,
  `ordered_fasting` varchar(10) DEFAULT NULL,
  `do_not_publish_to_patient` varchar(10) DEFAULT NULL,
  `interfacestatus` char(0) NOT NULL DEFAULT '',
  `created_datetime` date NOT NULL,
  `created_by` varchar(2) NOT NULL DEFAULT '',
  `ehr_source_name` varchar(9) NOT NULL DEFAULT '',
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `Result_Document_ID` double DEFAULT NULL,
  `Report_date` datetime DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_labs_udm_inc_id` (`udm_inc_id`),
  KEY `idx_eid` (`eid`),
  KEY `idx_psid` (`psid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_resdt` (`result_date`),
  KEY `id_resultid` (`result_id`)
) ENGINE=InnoDB AUTO_INCREMENT=91226088 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `radiology` (
  `result_id` varchar(30) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_date` datetime DEFAULT NULL,
  `img_date` varchar(100) DEFAULT NULL,
  `study_name` varchar(255) DEFAULT NULL,
  `modality` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `img_status` varchar(30) DEFAULT NULL,
  `img_report_text` longtext,
  `img_finding` longtext,
  `report_id` varchar(30) DEFAULT NULL,
  `report_date` varchar(100) DEFAULT NULL,
  `report_status` varchar(15) DEFAULT NULL,
  `img_reason` longtext,
  `order_date` date DEFAULT NULL,
  `order_status` varchar(30) DEFAULT NULL,
  `order_prescription` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider_id` varchar(20) DEFAULT NULL,
  `provider_name` varchar(130) DEFAULT NULL,
  `provider_npi` varchar(30) DEFAULT NULL,
  `internal_notes` text,
  `note_to_patient` text,
  `facility` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interpretation` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `report_text` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_datetime` date DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_radiology_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_psid` (`psid`),
  KEY `idx_eid` (`eid`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_result_id` (`result_id`),
  KEY `idx_enc_date_proxy` (`enc_date_proxy`)
) ENGINE=InnoDB AUTO_INCREMENT=6063730 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `ros` (
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `ros_date` date DEFAULT NULL,
  `ros_name` varchar(255) DEFAULT NULL,
  `ros_category` varchar(255) DEFAULT NULL,
  `ros_option` longtext,
  `ros_notes` longtext,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(15) DEFAULT NULL,
  `data_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `ros_id` varchar(255) DEFAULT NULL,
  `ros_parameter` varchar(255) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_ros_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_ros_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=130157108 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `examination` (
  `examid` varchar(30) DEFAULT NULL,
  `ndid` bigint DEFAULT NULL,
  `eid` bigint DEFAULT NULL,
  `enc_start_date` date DEFAULT NULL,
  `exam_date` date DEFAULT NULL,
  `exam_category` varchar(255) DEFAULT NULL,
  `exam_name` varchar(255) DEFAULT NULL,
  `exam_findings` longtext,
  `created_datetime` datetime NOT NULL,
  `created_by` varchar(30) DEFAULT NULL,
  `ehr_source_name` varchar(10) DEFAULT NULL,
  `source_path` varchar(12) NOT NULL DEFAULT '',
  `data_type` varchar(10) NOT NULL DEFAULT '',
  `psid` int NOT NULL DEFAULT '0',
  `finding_type` varchar(5000) DEFAULT NULL,
  `exam_parameters` varchar(500) DEFAULT NULL,
  `nd_extracted_date` date DEFAULT NULL,
  `udm_inc_id` bigint NOT NULL AUTO_INCREMENT,
  `enc_date_proxy` date DEFAULT NULL,
  UNIQUE KEY `UQ_examination_inc_udm_inc_id` (`udm_inc_id`),
  KEY `idx_ndid` (`ndid`),
  KEY `idx_examinations_01282026` (`psid`) USING BTREE,
  KEY `idx_eid` (`eid`)
) ENGINE=InnoDB AUTO_INCREMENT=90367494 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



